name: Build Executables

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            output_name: DossierBancaire.exe
            artifact_name: DossierBancaire-Windows.exe
          - os: macos-latest
            output_name: DossierBancaire
            artifact_name: DossierBancaire-Mac.app

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt
    
    - name: Build with PyInstaller (Windows)
      if: runner.os == 'Windows'
      run: |
        pyinstaller --onefile --windowed --name DossierBancaire --icon=NONE app.py
    
    - name: Build with PyInstaller (Mac)
      if: runner.os == 'macOS'
      run: |
        pyinstaller --onefile --windowed --name DossierBancaire app.py
    
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/${{ matrix.artifact_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}